#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

// display all errors
error_reporting(E_ALL);
ini_set('error_reporting', E_ALL);
ini_set('display_errors',1);

// require helpers
require_once 'helpers.php';

// require composer autoloader
require_once 'vendor/autoload.php';

$application = new Application();
$application->add(new \App\Library\Framework\Command\Space\Migrate\Up());
$application->add(new \App\Library\Framework\Command\Space\Migrate\Down());
$application->run();
